### ISSUE TITLE
[Discussion] Use LevelUp with a group

### ISSUE THREAD

**Issue by GeekOnCoffee** [jmmastey/level_up#71]
We just had our first real Ruby training in Green Bay a month or so ago. I'm now looking for something to continue the learning, and I think LevelUp would be great. 

`/users` is a great start (though it's unclear how to set a user's organization other than via the console) and there's likely a lot more data that would be useful to support the mentor/mentee relationship. 

I think there's some gaps in my understanding of how the workflow should work for a group, so maybe some documentation on that would help as well. 

@jmmastey mentioned he had some thoughts and this would be a good place to start, any features that will be beneficial to the global codebase I'd be potentially looking at submitting pull requests for.

**Comment by jmmastey** [comment]
Hey @GeekOnCoffee, sorry for taking so long to respond. Long week. Some general and some specific thoughts / questions:

0. Awesome! How was the training? What sort of group are you trying to run (e.g. focused like a bootcamp, evenings and/or weekends, whenever people get time?)
1. There are a lot of features that might be useful, I just haven't built them yet. Tagging orgs outside the console is one of those. For the purposes of your group, I'm perfectly happy to just tag people in the console in the same way, or you're welcome to submit a pull. There are some open issues for visualizations around progress that would be good as well.
2. For the most part, our workflow is dictated more than a little by our corporate hiring. It looks like the following:
- New hires come in, usually one or two a week. They're batched up a bit into a "cohort".
- Everyone -- regardless of role -- is asked to complete Engineering Baseline I as part of their onboarding process, so that we can have some consistency in our tech across the department. Other courses are at-will.
- Each new hire forks the https://github.com/jmmastey/level_up_exercises/ repo and then starts into the exercises at their own pace. They meet as part of their cohort (usually two or three times per week) to code review as a group. This is one of the more valuable things we do.
- When an assignment is completed, they submit a PR for it against the exercises repo. This is currently the easiest way for me to track them. For your group, depending on size, you could probably just do the same. You'd probably get some Enova folks reviewing your code ;) If you have your own mentors, you could fork the exercises repo and just submit against that repo.
- Either way, a more experienced developer who has already done the given assignment will review it and provide notes. The learner is given as much feedback as possible, and we try to do it in under 24 hours. I'd like to get to 2 reviewers and < 12 hours in the future, as this feedback loop is _the most important thing_. The learner may need to resubmit multiple times depending on how much correction is necessary.

Right now, if someone gets stuck, they often come ask one of the mentors in person, and each person has an experienced "buddy" as a new hire. Saturating learners in more-experienced mentors has been really successful, though sometimes matters of taste become a bit contentious.

Either way, let me know how to help you facilitate your group. I'd like to get more non-Enova people onboard over time, and this would be a great way iron out wrinkles. Liberal use of the Feedback button is also quite appreciated.

**Comment by GeekOnCoffee** [comment]
No worries! I was actually not involved with the training, but they used the Railsbridge curriculum (or some form of it at least). I anticipate it being a "whenever people get time", as I'm not in a position to facilitate a focused scheduled group. 

Are cohorts treated as organizations in the system, or is that simply an informal social structure? 

I assume those pull requests never get merged, it's just a mechanism for a diff to review? 

I'll have to think this over and figure out what my next steps are :)

**Comment by jmmastey** [comment]
Cohorts are informal, and tend to bleed together. People who want to do more code reviews as a group will just show up for other cohorts' reviews. Those folks are much more successful than average.

PRs are always closed, yeah. I've had to add a few maintainers to the level_up_exercises repo to let people other than me manage it. Take a look at github.com/jmmastey/level_up_exercises/pulls.

Honestly, that repo also has interesting reference solutions + feedback for every assignment at this point. You could probably review those as a group as well to get ideas on implementations when stuck.

**Comment by jmmastey** [comment]
Closing this as it's quite old. Feel free to re-open if there is an outstanding issue.
